import { useState } from 'react';
import { useWorkspaceRequest } from './workspace-context.js';
import { installationLink } from './installation-model.js';
import { accountDestination } from './auth-navigation.js';
import './accounts.css';

export function Installation({auth,embedded=false}){
  const config=auth.config?.installation||{},store=installationLink(config.storeUrl,{store:true}),video=installationLink(config.videoUrl),download=installationLink(config.downloadUrl)||'/downloads/recall-extension.zip';
  const steps=store?[['Add Recall to Chrome','Open the store link and choose Add to Chrome.'],['Return to Recall','Refresh this website tab to connect your login.']]:[['Download and extract','Extract the ZIP into a folder you will keep.'],['Open Chrome Extensions','Enter chrome://extensions in the address bar and turn on Developer mode.'],['Load unpacked','Choose Load unpacked and select the extracted folder containing manifest.json.'],['Return to this tab','Refresh Recall to connect your website login. No second password is needed.']];
  return <section className="installation-page" aria-labelledby="install-title">
    <div className="installation-heading"><div><p className="eyebrow">Desktop Chrome · Same profile as LeetCode</p>{embedded?<h2 id="install-title">Install Recall.</h2>:<h1 id="install-title">Bring Recall<br /><span>to your browser.</span></h1>}<p className="page-description">Record practice after an accepted submission. On mobile? Return here on your computer when ready.</p></div><a className="primary-button" href={store||download} {...(store?{target:'_blank',rel:'noopener noreferrer'}:{download:'recall-extension.zip'})}>{store?'Add to Chrome':'Download extension'} ↗</a></div>
    <div className={'installation-body '+(video?'':'installation-without-video')}>{video&&<div className="installation-video"><video controls preload="metadata" src={video}><a href={video}>Watch the installation walkthrough</a></video></div>}<div className="installation-instructions"><ol>{steps.map(([title,description],index)=><li key={title}><span>{index+1}</span><div><h3>{title}</h3><p>{description}</p></div></li>)}</ol><p className="installation-note">{store?'Chrome updates the extension automatically.':'Keep the extracted folder. To update, replace its files and click Reload in Chrome Extensions.'} Refresh Recall and LeetCode after an update.</p></div></div>
    {!embedded&&<div className="installation-footer"><p>Connection and import progress are available together on Recall.</p><a className="primary-button" href="#/connect">Check connection →</a><a className="inline-link" href={auth.user?'#/dashboard':'#/signup'}>{auth.user?'Set up later':'Create account'}</a></div>}
  </section>;
}

export default function Onboarding({auth}){
  const request=useWorkspaceRequest();
  const [profile,setProfile]=useState(auth.setup?.goal?.profile||'interview'),[target,setTarget]=useState(auth.setup?.goal?.target||300),[busy,setBusy]=useState(false),[error,setError]=useState('');
  async function save(){setBusy(true);setError('');try{await request('/setup',{method:'PUT',body:JSON.stringify({profile,target,completed:true})});const account=await auth.refresh();window.location.hash=accountDestination(account.setup);}catch(e){setError(e.message);}finally{setBusy(false);}}
  return <section className="goal-onboarding" aria-labelledby="setup-title"><p className="eyebrow">A starting point, not a commitment</p><h1 id="setup-title">What are you<br /><span>working toward?</span></h1><p className="page-description">Choose your focus. Connect LeetCode whenever you are ready.</p><form onSubmit={event=>{event.preventDefault();if(!busy)void save();}}><fieldset disabled={busy}><legend>Preparation mode</legend>{[['interview','Interview focused','Give interview-relevant patterns more emphasis.','↗'],['deep','Deep understanding','Build a broader foundation across patterns.','✳']].map(([value,title,description,symbol])=><label className={'setup-mode-option '+(profile===value?'setup-mode-selected':'')} key={value}><input type="radio" name="profile" value={value} checked={profile===value} onChange={()=>setProfile(value)} /><span><strong>{title}</strong><span>{description}</span></span><i aria-hidden="true">{symbol}</i></label>)}</fieldset><details className="goal-settings"><summary>Adjust starting goal · {target} problems</summary><label className="setup-target" htmlFor="setup-target">Balanced coverage target<select id="setup-target" value={target} disabled={busy} onChange={e=>setTarget(Number(e.target.value))}>{[300,500,1000].map(value=><option key={value} value={value}>{value} problems</option>)}</select><small>A target across patterns and difficulty, not a daily quota. Change it later on your dashboard.</small></label></details><button className="primary-button" disabled={busy}>{busy?'Saving…':'Open my workspace'} →</button></form><p className="account-error" role="alert">{error}</p></section>;
}
