import './public.css';
export default function Privacy(){
  return <div className="public-page privacy-page"><header className="public-hero privacy-intro"><div><p className="eyebrow">Your practice. Your data.</p><h1>Privacy, in plain words.</h1><p className="public-lead">What Recall records, where it lives, and the controls you have.</p><p className="data-note">Updated 10 October 2026 · Current preview</p></div></header>
    <section className="privacy-section"><span className="privacy-number" aria-hidden="true">01</span><div><h2>What you share</h2><p>Your Recall account uses an email address and password through Supabase Auth. Recall also stores your goal, preparation mode, LeetCode username, solved problem metadata, selected patterns, recorded practice dates, assistance choices and any notes you add.</p><p>The extension reads problem details, accepted-problem status and available recent accepted submissions from your signed-in LeetCode session. Recall does not ask for your LeetCode password or collect your solution code.</p></div></section>
    <section className="privacy-section"><span className="privacy-number" aria-hidden="true">02</span><div><h2>Where it lives</h2><p>In local mode, practice data lives in your configured PostgreSQL database. When accounts are enabled, Recall keeps each verified account in a separate database workspace. Local development workspaces remain separate from hosted accounts.</p><p>Supabase handles authentication and email confirmation/recovery. The website keeps your session in browser storage. The extension keeps its account tokens in Chrome session storage and its drafts, queues and import checkpoints in account-specific local storage.</p><p>In the hosted Render preview, Render runs the website/API and Supabase stores account and practice data. Hosting providers process network requests and may retain operational logs. This preview does not add advertising or analytics trackers.</p></div></section>
    <section className="privacy-section"><span className="privacy-number" aria-hidden="true">03</span><div><h2>Why it is used</h2><p>Problem metadata and practice records power classification, goal coverage and your practice queue. Recency and assistance contribute to estimated practice strength. These bars estimate practice evidence; they do not measure your memory or interview success.</p><p>Account identity protects your workspace. Import checkpoints and request IDs help recover interrupted saves without counting the same recording twice.</p><p>Recall also maintains account summaries for running the service: name, email, signup and onboarding status, usage counts, last meaningful activity, and the extension’s last reported connection and version. The private owner dashboard requires assigned permissions and an authenticator code. It shows masked emails by default; revealing a full email requires separate permission and a recorded support reason. It does not expose your practice notes or solution code.</p><p>Operational diagnostics record an account ID, operation, outcome code, version, request timing and received time. These records exclude passwords, tokens, solution code and problem notes. Diagnostics and aggregate API timings are retained for 30 days; owner access logs for 90 days. Account deletion removes its operational profile and diagnostics, and clears related free-text support reasons. Minimal account IDs remain in security records to prevent deleted accounts from being recreated. This collection uses Recall’s own service, with no advertising or third-party analytics tracker.</p></div></section>
    <section className="privacy-section"><span className="privacy-number" aria-hidden="true">04</span><div><h2>Your controls</h2><p>In Settings, download a restorable practice backup, export your account data, and correct or recover recordings. Signing out removes that browser’s active session; it does not erase your saved practice.</p><p>When account deletion is configured, it requires your current password and typed confirmation. It removes your Recall database workspace and Supabase login. If either service is unavailable, the request remains queued and workspace access is blocked while cleanup retries. A minimal record of the account ID and deletion state remains to stop old requests from recreating the workspace.</p><p>Account deletion does not remove provider backups, JSON exports you downloaded, or drafts stored in another browser’s extension. Uninstall Recall from those Chrome profiles to clear their extension storage. Old local workspaces are separate from your online account.</p><a className="secondary-button" href="#/settings">Open data controls <span aria-hidden="true">↗</span></a></div></section>
    <section className="privacy-section"><span className="privacy-number" aria-hidden="true">05</span><div><h2>Limits of this preview</h2><p>Recall is an independent project and is not affiliated with LeetCode. Browser storage can be cleared and hosting services have their own retention policies. Keep a downloaded backup of practice you want to preserve.</p><p>Before a wider public launch, the project still needs a support/privacy contact and a documented operational backup retention policy. These details will be updated here when the service is configured.</p><a className="inline-link" href="/about">About Recall</a></div></section>
  </div>;
}
